### ISSUE TITLE
Example isn't working

### ISSUE THREAD

**Issue by jonaswindey** [lipp/next-todos#6]
Example isn't working and gives following error:

```
VM50:37 WebSocket connection to 'wss://todos-demo.now.sh/' failed: Error during WebSocket handshake: Unexpected response code: 200
```

**Comment by lipp** [comment]
This is a current now issue

**Comment by lipp** [comment]
https://github.com/zeit/now-cli/issues/192#issuecomment-269762922

Will restart as soon as I'm on computer

**Comment by jamo** [comment]
It seems to be working again 😊

**Comment by lipp** [comment]
THX for reporting 👍  
Hope you like this project :)
